apiVersion: v1
kind: Service
metadata:
  name: {{ template "php-fpm.fullname" . }}
  labels:
    app: {{ template "php-fpm.name" . }}
    chart: {{ template "php-fpm.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: php-fpm
      protocol: TCP
      name: php-fpm
  selector:
    app: {{ template "php-fpm.name" . }}
    release: {{ .Release.Name }}
