apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  nginx.conf: |
{{ .Files.Get "files/nginx.conf" | indent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: sites-conf
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{ (.Files.Glob "files/sites/*.conf").AsConfig | indent 2 }}