apiVersion: v1
kind: Service
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.httpPort }}
    {{- end }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- if contains "NodePort" .Values.service.type }}
      nodePort: {{ .Values.service.httpsPort }}
    {{- end }}
  selector:
    app: {{ template "nginx.name" . }}
    release: {{ .Release.Name }}
