apiVersion: v1
kind: Service
metadata:
  name: {{ template "beanstalkd.fullname" . }}
  labels:
    app: {{ template "beanstalkd.name" . }}
    chart: {{ template "beanstalkd.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: beanstalkd
      port: {{ .Values.service.port }}
      targetPort: beanstalkd
      protocol: TCP
  selector:
    app: {{ template "beanstalkd.name" . }}
    release: {{ .Release.Name }}
